import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Sparkles, 
  Bot, 
  ArrowRight, 
  RefreshCw, 
  Check, 
  AlertCircle, 
  Wand2, 
  X, 
  Sliders, 
  FileText, 
  Layers, 
  Hash, 
  Zap, 
  Lightbulb, 
  ChevronRight, 
  BookOpen 
} from 'lucide-react';
import { crmApi } from '../../../data/crmApi';
import { NEUORZIN_SERVICE_CATEGORIES, getAllRecommendedTopics } from '../../../data/serviceCategories';

export function GeminiBlogGeneratorModal({ isOpen, onClose, onApplyContent, onShowToast, categories = [] }) {
  const [topic, setTopic] = useState('');
  const [targetAudience, setTargetAudience] = useState('CTOs, VPs of Engineering, Enterprise Decision-Makers');
  const [tone, setTone] = useState('Authoritative, Strategic & Practical');
  const [length, setLength] = useState('Comprehensive (1,500+ words)');
  const [category, setCategory] = useState(categories[0]?.name || 'Sales & Marketing Growth Engines');
  const [keywords, setKeywords] = useState('');
  const [instructions, setInstructions] = useState('');
  
  const [activeTab, setActiveTab] = useState('prompt'); // 'prompt' | 'recommendations'
  const [selectedPillarFilter, setSelectedPillarFilter] = useState('All');

  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedData, setGeneratedData] = useState(null);
  const [errorMsg, setErrorMsg] = useState('');

  if (!isOpen) return null;

  const handleApplyRecommendation = (rec) => {
    setTopic(rec.title);
    if (rec.category) setCategory(rec.category);
    if (Array.isArray(rec.keywords)) setKeywords(rec.keywords.join(', '));
    if (rec.tone) setTone(rec.tone);
    if (rec.length) setLength(rec.length);
    if (rec.excerpt) setInstructions(`Focus on addressing: ${rec.excerpt}`);
    setActiveTab('prompt');
    if (onShowToast) onShowToast(`Loaded recommendation: "${rec.title.slice(0, 40)}..."`, 'info');
  };

  const handleGenerate = async (e) => {
    if (e) e.preventDefault();
    if (!topic.trim()) {
      setErrorMsg('Please provide an article topic or headline idea.');
      return;
    }

    setIsGenerating(true);
    setErrorMsg('');
    try {
      const res = await crmApi.generateBlogWithGemini({
        topic: topic.trim(),
        audience: targetAudience,
        tone,
        length,
        category,
        keywords: keywords.trim(),
        instructions: instructions.trim()
      });

      if (res && res.data) {
        setGeneratedData(res.data);
        if (onShowToast) onShowToast('✨ Article draft successfully generated by Gemini AI!', 'success');
      } else {
        throw new Error(res.error || 'Failed to generate blog content');
      }
    } catch (err) {
      setErrorMsg(err.message || 'Error communicating with Gemini API. Check your API key in Settings.');
      if (onShowToast) onShowToast(err.message || 'Generation failed', 'error');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleApply = () => {
    if (!generatedData) return;
    if (onApplyContent) {
      onApplyContent(generatedData);
    }
    onClose();
  };

  // Recommendations filtered by pillar
  const allRecs = getAllRecommendedTopics();
  const filteredRecs = selectedPillarFilter === 'All' 
    ? allRecs 
    : allRecs.filter(r => r.pillar === selectedPillarFilter);

  const pillars = ['All', 'Growth & Marketing', 'Product Intelligence', 'Data & AI', 'Cloud Platform', 'Quantum Computing'];

  // Combined Category List
  const serviceCatNames = NEUORZIN_SERVICE_CATEGORIES.map(s => s.name);
  const extraCatNames = categories.map(c => c.name).filter(n => !serviceCatNames.includes(n));

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-slate-950/70 backdrop-blur-xs overflow-y-auto">
      <motion.div
        initial={{ opacity: 0, scale: 0.95, y: 10 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.95, y: 10 }}
        className="relative w-full max-w-4xl bg-white border border-slate-200 rounded-3xl shadow-2xl overflow-hidden my-6 max-h-[90vh] flex flex-col"
      >
        {/* Header */}
        <div className="p-5 sm:p-6 bg-gradient-to-r from-purple-50 via-indigo-50/50 to-transparent border-b border-slate-200 flex items-center justify-between shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-2xl bg-gradient-to-tr from-purple-600 to-indigo-600 text-white flex items-center justify-center shadow-md shadow-indigo-500/20">
              <Sparkles className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-base sm:text-lg font-black text-slate-900 font-display">
                  Gemini AI Article Engine & Recommendations
                </h3>
                <span className="px-2 py-0.5 rounded-full bg-purple-100 text-purple-800 text-[10px] font-bold uppercase tracking-wider">
                  Server-Side AI
                </span>
              </div>
              <p className="text-xs text-slate-500 mt-0.5">
                Generate high-authority, SEO-optimized articles with structured sections and service auto-fill.
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            {/* Tab Switcher */}
            <div className="flex bg-slate-100 p-1 rounded-xl text-xs font-semibold">
              <button
                type="button"
                onClick={() => setActiveTab('prompt')}
                className={`px-3 py-1.5 rounded-lg transition-all cursor-pointer ${
                  activeTab === 'prompt' ? 'bg-white text-purple-700 shadow-xs font-bold' : 'text-slate-600 hover:text-slate-900'
                }`}
              >
                Prompt Generator
              </button>
              <button
                type="button"
                onClick={() => setActiveTab('recommendations')}
                className={`px-3 py-1.5 rounded-lg transition-all flex items-center gap-1.5 cursor-pointer ${
                  activeTab === 'recommendations' ? 'bg-white text-purple-700 shadow-xs font-bold' : 'text-slate-600 hover:text-slate-900'
                }`}
              >
                <Lightbulb className="w-3.5 h-3.5 text-amber-500" />
                <span>AI Recommendations ({allRecs.length})</span>
              </button>
            </div>

            <button
              onClick={onClose}
              className="p-2 rounded-xl text-slate-400 hover:text-slate-700 hover:bg-slate-100 transition-colors cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Scrollable Content Body */}
        <div className="p-5 sm:p-6 overflow-y-auto space-y-6 flex-1 text-left">
          {errorMsg && (
            <div className="p-4 rounded-2xl bg-rose-50 border border-rose-200 text-rose-700 text-xs flex items-start gap-3">
              <AlertCircle className="w-4 h-4 shrink-0 mt-0.5" />
              <div className="flex-1">
                <strong>Generation Notice: </strong> {errorMsg}
              </div>
            </div>
          )}

          {/* TAB 1: RECOMMENDATIONS BROWSER */}
          {activeTab === 'recommendations' && (
            <div className="space-y-4">
              <div className="flex flex-wrap items-center justify-between gap-3 pb-2 border-b border-slate-100">
                <div className="flex items-center gap-2">
                  <Lightbulb className="w-4 h-4 text-amber-500" />
                  <span className="text-xs font-bold text-slate-700 uppercase tracking-wider">
                    Select a Recommended Topic by Service Pillar
                  </span>
                </div>
                <div className="flex flex-wrap gap-1">
                  {pillars.map(pillar => (
                    <button
                      key={pillar}
                      type="button"
                      onClick={() => setSelectedPillarFilter(pillar)}
                      className={`px-2.5 py-1 rounded-lg text-[11px] font-semibold transition-all cursor-pointer ${
                        selectedPillarFilter === pillar
                          ? 'bg-purple-100 text-purple-900 font-bold'
                          : 'bg-slate-100 text-slate-600 hover:text-slate-900'
                      }`}
                    >
                      {pillar}
                    </button>
                  ))}
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-3.5">
                {filteredRecs.map((rec, idx) => (
                  <div
                    key={idx}
                    className="p-4 rounded-2xl bg-slate-50 border border-slate-200 hover:border-purple-300 hover:bg-purple-50/20 transition-all flex flex-col justify-between space-y-3 group"
                  >
                    <div className="space-y-1.5">
                      <div className="flex items-center justify-between text-[10px]">
                        <span className="px-2 py-0.5 rounded-full bg-purple-100 text-purple-800 font-bold uppercase tracking-wider">
                          {rec.pillar}
                        </span>
                        <span className="text-slate-400 font-medium">{rec.length}</span>
                      </div>
                      <h4 className="text-xs sm:text-sm font-bold text-slate-900 group-hover:text-purple-700 transition-colors leading-snug">
                        {rec.title}
                      </h4>
                      <p className="text-[11px] text-slate-500 line-clamp-2 leading-relaxed">
                        {rec.excerpt}
                      </p>
                    </div>

                    <div className="pt-2 border-t border-slate-200/60 flex items-center justify-between">
                      <div className="flex flex-wrap gap-1">
                        {rec.keywords.slice(0, 2).map((k, ki) => (
                          <span key={ki} className="text-[10px] text-slate-400 font-mono">
                            #{k}
                          </span>
                        ))}
                      </div>

                      <button
                        type="button"
                        onClick={() => handleApplyRecommendation(rec)}
                        className="px-3 py-1.5 rounded-xl bg-purple-600 hover:bg-purple-700 text-white text-xs font-bold flex items-center gap-1.5 shadow-xs transition-transform group-hover:translate-x-0.5 cursor-pointer"
                      >
                        <span>Use This Topic</span>
                        <ArrowRight className="w-3 h-3" />
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* TAB 2: PROMPT FORM & GENERATED OUTPUT */}
          {activeTab === 'prompt' && !generatedData && (
            <form onSubmit={handleGenerate} className="space-y-4">
              <div>
                <div className="flex justify-between items-center mb-1.5">
                  <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider">
                    Article Topic / Core Headline Idea <span className="text-red-500">*</span>
                  </label>
                  <button
                    type="button"
                    onClick={() => setActiveTab('recommendations')}
                    className="text-xs font-bold text-purple-600 hover:underline flex items-center gap-1 cursor-pointer"
                  >
                    <Lightbulb className="w-3 h-3 text-amber-500" />
                    <span>Browse AI Recommendations</span>
                  </button>
                </div>
                <input
                  type="text"
                  required
                  placeholder="e.g. How We Built a Real-Time Snowflake Data Mesh for Multi-Region Telemetry"
                  value={topic}
                  onChange={(e) => setTopic(e.target.value)}
                  className="w-full px-4 py-2.5 rounded-xl bg-slate-50 border border-slate-200 text-xs sm:text-sm text-slate-900 focus:outline-none focus:border-purple-600 focus:bg-white transition-all shadow-xs"
                />
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1.5">
                    Category (Auto-Filled from NeuOrzin Services)
                  </label>
                  <select
                    value={category}
                    onChange={(e) => setCategory(e.target.value)}
                    className="w-full px-3.5 py-2.5 rounded-xl bg-slate-50 border border-slate-200 text-xs text-slate-900 font-bold focus:outline-none focus:border-purple-600 cursor-pointer"
                  >
                    <optgroup label="NeuOrzin Service Pillars">
                      {serviceCatNames.map(name => (
                        <option key={name} value={name}>{name}</option>
                      ))}
                    </optgroup>
                    {extraCatNames.length > 0 && (
                      <optgroup label="Custom Categories">
                        {extraCatNames.map(name => (
                          <option key={name} value={name}>{name}</option>
                        ))}
                      </optgroup>
                    )}
                  </select>
                </div>

                <div>
                  <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1.5">
                    Tone & Voice
                  </label>
                  <select
                    value={tone}
                    onChange={(e) => setTone(e.target.value)}
                    className="w-full px-3.5 py-2.5 rounded-xl bg-slate-50 border border-slate-200 text-xs text-slate-900 font-bold focus:outline-none focus:border-purple-600 cursor-pointer"
                  >
                    <option value="Authoritative, Strategic & Practical">Authoritative, Strategic & Practical (Recommended)</option>
                    <option value="Hardcore Engineering & Benchmark-Heavy">Hardcore Engineering & Benchmark-Heavy</option>
                    <option value="Executive Briefing & C-Level ROI">Executive Briefing & C-Level ROI</option>
                    <option value="Practitioner Teardown & Case Study">Practitioner Teardown & Case Study</option>
                    <option value="Analytical & Technical Tutorial">Analytical & Technical Tutorial</option>
                  </select>
                </div>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1.5">
                    Target Audience
                  </label>
                  <input
                    type="text"
                    value={targetAudience}
                    onChange={(e) => setTargetAudience(e.target.value)}
                    placeholder="e.g. CTOs, Engineering Leaders, Growth Marketers"
                    className="w-full px-3.5 py-2.5 rounded-xl bg-slate-50 border border-slate-200 text-xs text-slate-900 focus:outline-none focus:border-purple-600 focus:bg-white"
                  />
                </div>

                <div>
                  <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1.5">
                    Article Depth & Length
                  </label>
                  <select
                    value={length}
                    onChange={(e) => setLength(e.target.value)}
                    className="w-full px-3.5 py-2.5 rounded-xl bg-slate-50 border border-slate-200 text-xs text-slate-900 font-bold focus:outline-none focus:border-purple-600 cursor-pointer"
                  >
                    <option value="Comprehensive (1,500 - 2,000 words)">Comprehensive Architecture (1,500 - 2,000 words)</option>
                    <option value="Deep Blueprint (2,000 - 3,000 words)">Deep Technical Blueprint (2,000 - 3,000 words)</option>
                    <option value="In-Depth Guide (1,000 - 1,500 words)">In-Depth Guide (1,000 - 1,500 words)</option>
                    <option value="Focused Executive Brief (800 - 1,200 words)">Focused Executive Brief (800 - 1,200 words)</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1.5">
                  Target SEO Keywords (Comma Separated)
                </label>
                <input
                  type="text"
                  placeholder="e.g. Snowflake Migration, CDC Streaming, dbt Data Mesh, Telemetry"
                  value={keywords}
                  onChange={(e) => setKeywords(e.target.value)}
                  className="w-full px-3.5 py-2.5 rounded-xl bg-slate-50 border border-slate-200 text-xs text-slate-900 focus:outline-none focus:border-purple-600 focus:bg-white"
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1.5">
                  Specific Real-World Examples or Custom Directives
                </label>
                <textarea
                  rows="2"
                  placeholder="e.g. Include a benchmark comparison table between BM25 sparse search and ColBERT dense vector rerankers."
                  value={instructions}
                  onChange={(e) => setInstructions(e.target.value)}
                  className="w-full px-3.5 py-2 rounded-xl bg-slate-50 border border-slate-200 text-xs text-slate-900 focus:outline-none focus:border-purple-600 focus:bg-white resize-none"
                />
              </div>

              {/* Submit CTA */}
              <div className="pt-3 flex justify-end gap-3">
                <button
                  type="button"
                  onClick={onClose}
                  className="px-5 py-2.5 rounded-xl border border-slate-200 hover:bg-slate-50 text-slate-700 text-xs font-bold cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={isGenerating || !topic.trim()}
                  className="px-6 py-2.5 rounded-xl bg-gradient-to-r from-purple-600 via-indigo-600 to-blue-600 hover:from-purple-700 hover:to-blue-700 disabled:opacity-50 text-white text-xs font-bold shadow-md shadow-indigo-500/20 flex items-center gap-2 cursor-pointer transition-all"
                >
                  {isGenerating ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Wand2 className="w-4 h-4" />}
                  <span>{isGenerating ? 'Synthesizing with Gemini AI...' : 'Generate Full Article'}</span>
                </button>
              </div>
            </form>
          )}

          {/* GENERATED CONTENT REVIEW SCREEN */}
          {activeTab === 'prompt' && generatedData && (
            <div className="space-y-5">
              <div className="p-4 rounded-2xl bg-emerald-50 border border-emerald-200 text-emerald-900 text-xs flex items-center justify-between">
                <div className="flex items-center gap-2 font-bold">
                  <Check className="w-4 h-4 text-emerald-600" />
                  <span>Draft synthesized successfully! Review details below before loading into Editor.</span>
                </div>
                <button
                  type="button"
                  onClick={() => setGeneratedData(null)}
                  className="text-xs text-emerald-800 underline font-bold cursor-pointer"
                >
                  Regenerate / Adjust
                </button>
              </div>

              {/* Title & Metadata */}
              <div className="space-y-2 p-5 rounded-2xl bg-slate-50 border border-slate-200">
                <span className="px-2.5 py-0.5 rounded-full bg-purple-100 text-purple-800 font-bold text-[10px] uppercase">
                  {generatedData.category || category}
                </span>
                <h2 className="text-lg sm:text-xl font-black text-slate-900">
                  {generatedData.title}
                </h2>
                <p className="text-xs text-slate-600 leading-relaxed italic">
                  "{generatedData.excerpt}"
                </p>
                <div className="flex flex-wrap items-center gap-3 pt-2 text-[11px] text-slate-500">
                  <span>Slug: <strong>/{generatedData.slug}</strong></span>
                  <span>•</span>
                  <span>Estimated: <strong>{generatedData.readTime || '6 min read'}</strong></span>
                </div>
              </div>

              {/* Body Sections Preview */}
              <div className="space-y-3">
                <h4 className="text-xs font-bold text-slate-700 uppercase tracking-wider">
                  Generated Outline & Content ({generatedData.sections?.length || 0} Sections)
                </h4>
                {(generatedData.sections || []).map((sec, idx) => (
                  <div key={idx} className="p-4 rounded-xl bg-white border border-slate-200 space-y-2 text-xs">
                    <div className="font-bold text-slate-900">{sec.heading}</div>
                    {sec.paragraphs?.map((p, pi) => (
                      <p key={pi} className="text-slate-600 leading-relaxed">{p}</p>
                    ))}
                    {sec.callout && (
                      <div className="p-3 rounded-lg bg-blue-50 border-l-4 border-[#0070ba] text-[#0070ba] italic font-medium">
                        {sec.callout}
                      </div>
                    )}
                    {sec.list && (
                      <ul className="list-disc pl-5 space-y-1 text-slate-600">
                        {sec.list.map((li, lidx) => (
                          <li key={lidx}>{li}</li>
                        ))}
                      </ul>
                    )}
                  </div>
                ))}
              </div>

              {/* Apply Action Buttons */}
              <div className="pt-3 border-t border-slate-200 flex justify-end gap-3">
                <button
                  type="button"
                  onClick={() => setGeneratedData(null)}
                  className="px-5 py-2.5 rounded-xl border border-slate-200 hover:bg-slate-50 text-slate-700 text-xs font-bold"
                >
                  Discard & Re-Prompt
                </button>
                <button
                  type="button"
                  onClick={handleApply}
                  className="px-6 py-2.5 rounded-xl bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-700 hover:to-teal-700 text-white text-xs font-bold shadow-md shadow-emerald-500/20 flex items-center gap-2 cursor-pointer"
                >
                  <Check className="w-4 h-4" />
                  <span>Load Into Editor & Polish</span>
                </button>
              </div>
            </div>
          )}
        </div>
      </motion.div>
    </div>
  );
}

export default GeminiBlogGeneratorModal;
